# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 520391708955ea5e6e36a67e175a7ba0a3b5cda1704800abca80c1de31c961cf4a1a7cf2ac0de8ca412c6d2182c93ddaf4fdd629edbc1ff37bd76b7c314fcd37

test:
  secret_key_base: 08b43e640f880a0e1dcc9c10bd9c5a864836c8c2fbce15935ad92fc502ae4ff4a73b02cc4790fb81e06cfea795791e5fab85bbfc7329a30f0da722408298732d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
